sudo: false

language: go

go:
  - '1.12.x'

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.23.1/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1

jobs:
  include:
    - stage: build
      script:
        - make test
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/bin/push-images; fi'
    - stage: coverage
      script:
        - make coverage
    - stage: integration tests
      if: type != pull_request
      script:
        - sh build/bin/trigger-tests-travis $TRAVIS_ACCESS_TOKEN
    - stage: CLI build
      if: type != pull_request
      script:
        - sh build/bin/trigger-cli-travis $TRAVIS_ACCESS_TOKEN
