# SPDX-FileCopyrightText: 2019-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

onos-config:
  plugins:
    - name: devicesim
      version: 1.0.0
      image:
        repository: onosproject/config-model-devicesim-1.0.0
        tag: v0.6.20
        pullPolicy: IfNotPresent
    - name: stratum
      version: 1.0.0
      image:
        repository: onosproject/config-model-stratum-1.0.0
        tag: v0.6.20
        pullPolicy: IfNotPresent
    - name: testdevice
      version: 1.0.0
      image:
        repository: onosproject/config-model-testdevice-1.0.0
        tag: v0.6.20
        pullPolicy: IfNotPresent
    - name: testdevice
      version: 2.0.0
      image:
        repository: onosproject/config-model-testdevice-2.0.0
        tag: v0.6.20
        pullPolicy: IfNotPresent
