# SPDX-FileCopyrightText: 2019-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

setrequest:
  prefix:
    elem:
      - name: e2node
    target: ""
  delete: [ ]
  replace: [ ]
  update:
    - path:
        elem:
          - name: intervals
          - name: RadioMeasReportPerUe
        target: 315010-0001420
      val:
        uintvalue:
          uintval: 20
    - path:
        elem:
          - name: intervals
          - name: RadioMeasReportPerCell
        target: 315010-0001420
      val:
        uintvalue:
          uintval: 21
    - path:
        elem:
          - name: intervals
            key: { }
          - name: RadioMeasReportPerUe
            key: { }
        target: 315010-0001421
      val:
        uintvalue:
          uintval: 20
    - path:
        elem:
          - name: intervals
          - name: RadioMeasReportPerCell
        target: 315010-0001421
      val:
        uintvalue:
          uintval: 21
    - path:
        elem:
          - name: intervals
          - name: RadioMeasReportPerUe
        target: 315010-0001422
      val:
        uintvalue:
          uintval: 20
    - path:
        elem:
          - name: intervals
          - name: RadioMeasReportPerCell
        target: 315010-0001422
      val:
        uintvalue:
          uintval: 21
  extension:
    - id: 101
      value: 1.0.0
    - id: 102
      value: E2Node
