{{- if .Values.store.enabled }}
apiVersion: k8s.atomix.io/v1alpha1
kind: PartitionSet
metadata:
  name: {{ .Values.store.raftgroup }}
  namespace: {{ .Release.Namespace }}
  labels:
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
spec:
  partitions: {{ .Values.store.raft.partitions }}
  template:
    spec:
      size: {{ .Values.store.raft.partitionSize }}
      raft:
        electionTimeoutMillis: 5000
        heartbeatPeriodMillis: 1000
{{- end }}