apiVersion: v1
kind: Service
metadata:
  name: {{ template "onos-config.fullname" . }}
  labels:
    app: {{ template "onos-config.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "onos-config.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name: {{ template "onos-config.fullname" . }}
    app: onos
    type: config
    resource: {{ template "onos-config.fullname" . }}
    {{- include "onos-config.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 5150
