nameOverride: ""

replicas: 1
annotations: {}

image:
  repository: onosproject/onos-config
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

devices: []

store:
  enabled: false
  controller: atomix-controller.kube-system.svc.cluster.local:5679
  raft:
    partitions: 3
    partitionSize: 3

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

ingress:
  enabled: false
