# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
# Copyright 2024 Kyunghee University
name: Publish image and tag/release code

on:
  push:
    branches:
      - master

jobs:
  version-check:
    uses: onosproject/.github/.github/workflows/go-version-check.yml@main

  tag-versions:
    runs-on: ubuntu-latest
    needs: version-check
    if: needs.version-check.outputs.dev_version == 'false'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Github release
        uses: onosproject/.github/.github/actions/create-github-release-action@main
        with:
          version: v${{ needs.version-check.outputs.target_version }}
        env:
          GH_TOKEN: ${{ secrets.GH_ONOS_PAT }}

  publish-images:
    needs: version-check
    if: needs.version-check.outputs.dev_version == 'false'
    uses: onosproject/.github/.github/workflows/release-image.yml@main
    env:
      ONOS_CONFIG_VERSION: latest

  bump-up-version:
    needs: version-check
    if: needs.version-check.outputs.dev_version == 'false'
    uses: onosproject/.github/.github/workflows/bump-version.yml@main
    secrets: inherit
    with:
      version: ${{ needs.version-check.outputs.target_version }}
